list_contact:
    pattern:  /user/liste_contact
    defaults: { _controller: EieinstitutBundle:Usager:liste_contact }

supprimer_contact:
    pattern:  /user/supprimer_contact/{contact}
    defaults: { _controller: EieinstitutBundle:Usager:supprimer_contact }