ei_administration_homepage:
    pattern:  /admin/index
    defaults: { _controller: EiAdministrationBundle:Default:index }
    
ei_administration_actualite:
    pattern:  /admin/actualite
    defaults: { _controller: EiAdministrationBundle:Default:actualite } 
ei_administration_page:
    pattern:  /admin/page
    defaults: { _controller: EiAdministrationBundle:Default:page } 
    
ei_administration_ressources:
    pattern:  /admin/ressources
    defaults: { _controller: EiAdministrationBundle:Default:ressources }
    
ei_administration_listeuser:
    pattern:  /admin/users
    defaults: { _controller: EiAdministrationBundle:Default:listeuser }
    
ei_administration_listetuto:
    pattern:  /admin/listetuto
    defaults: { _controller: EiAdministrationBundle:Default:listetuto }
    
ei_administration_newsletter:
    pattern:  /admin/newsletter
    defaults: { _controller: EiAdministrationBundle:Default:newsletter }    
    
