ei_administration_homepage:
    pattern:  /
    defaults: { _controller: EiAdministrationBundle:Default:index }
eieinstitut:
    resource: "@EieinstitutBundle/Resources/config/routing.yml"
    prefix:   /