eieinstitut_homepage:
    pattern:  /
    defaults: { _controller: EieinstitutBundle:Default:index }

Ressources:
    pattern:  /ressources
    defaults: { _controller: EieinstitutBundle:Default:ressources }

Forum:
    pattern:  /forum
    defaults: { _controller: EieinstitutBundle:Default:forum }

eieinstitut_admin:
    pattern:  /admin
    defaults: { _controller: EieinstitutBundle:Default:admin }

Page:
    pattern:  /page
    defaults: { _controller: EieinstitutBundle:Default:page }

espace_personnel:
    pattern:  /espace_personnel
    defaults: { _controller: EieinstitutBundle:Default:espace_personnel }

Test:
    pattern:  /test_page
    defaults: { _controller: EieinstitutBundle:Default:test_page }

# Admin routes
Admin_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_admin.yml"

# Usager routes
Usager_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_usager.yml"

# Istitution routes
Istitution_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_istitution.yml"

# Security routes
Security_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_security.yml"