eieinstitut_homepage:
    pattern:  /
    defaults: { _controller: EieinstitutBundle:Default:index }

Espace_Personnel:
    pattern:  /espace_Personnel
    defaults: { _controller: EieinstitutBundle:Default:espace_Personnel }

Ressources:
    pattern:  /ressources
    defaults: { _controller: EieinstitutBundle:Default:ressources }

Ressources_Ajouter:
    pattern:  /ajouter_ressource
    defaults: { _controller: EieinstitutBundle:Default:ajouter_ressource }


Forum:
    pattern:  /forum
    defaults: { _controller: EieinstitutBundle:Default:forum }

Annuaire:
    pattern:  /annuaire
    defaults: { _controller: EieinstitutBundle:Default:annuaire }



eieinstitut_admin:
    pattern:  /admin
    defaults: { _controller: EieinstitutBundle:Default:admin }

Page:
    pattern:  /page
    defaults: { _controller: EieinstitutBundle:Default:page }

espace_personnel:
    pattern:  /espace_personnel
    defaults: { _controller: EieinstitutBundle:Default:espace_personnel }

Test:
    pattern:  /test_page
    defaults: { _controller: EieinstitutBundle:Default:test_page }

# footer routes
Footer_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_footer.yml"

# Admin routes
Admin_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_admin.yml"

# Usager routes
Usager_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_usager.yml"

# Istitution routes
Istitution_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_istitution.yml"

# Security routes
Security_:
    resource: "@EieinstitutBundle/Resources/config/routing/routing_security.yml"